# ----------- CONFIGURABLE START -----------
cription:      "C++独立开发者|欢迎来到 Bwar「空间」。"
url:              https://www.bwar.tech
signoff:          "Bwar" 
facebook_appid:   #bwar
#google_analytics: UA-101222464-1
share:            true 
# 分页
paginate: 15
paginate_path: "bwarpage:num"
gems: [jekyll-paginate]
links:
  - name:         首页
    url:          /
    external:     false
  - name:         项目
    url:          /project
    external:     false
  - name:         文章
    url:          /article
    external:     false
  - name:         归档
    url:          /archives
    external:     false
  - name:         标签
    url:          /tags
    external:     false
  - name:         关于
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"

